version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    groups:
       pip-deps:
          patterns:
            - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
    groups:
       action-deps:
          patterns:
            - "*"
